# Generated by Django 6.0.1 on 2026-02-02 06:36

import suggestions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(default=suggestions.models.generate_ref_id, max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('can_contact', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pain_point', models.TextField()),
                ('impact_tags', models.JSONField(default=list)),
                ('beneficiaries', models.CharField(max_length=255)),
                ('complexity', models.CharField(max_length=100)),
                ('seen_elsewhere', models.BooleanField(default=False)),
                ('seen_elsewhere_detail', models.TextField(blank=True, null=True)),
                ('additional_thoughts', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Review', 'Review'), ('Pilot', 'Pilot'), ('Implemented', 'Implemented'), ('Deferred', 'Deferred')], default='Review', max_length=20)),
                ('impact_score', models.IntegerField(default=5)),
                ('feasibility_score', models.IntegerField(default=5)),
                ('owner', models.CharField(default='Unassigned', max_length=255)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
