# Generated by Django 6.0.1 on 2026-02-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='pain_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
