# Generated by Django 6.0.1 on 2026-02-02 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_idea_pain_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='internal_notes',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='pain_point',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
